module-name: subscription-cleanup-job
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/subscription-cleanup-job:latest
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/*_test.go"
