name: unit tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
          cache-dependency-path: ./go.sum

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -coverprofile cover.out -v ./...

      - name: coveralls github action
        uses: coverallsapp/github-action@v2.3.6
        with:
          format: golang
          file: ./cover.out
          fail-on-error: false
